import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#092325",
    padding: 24,
  },
  title: {
    marginTop: "20%",
    fontSize: 25,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  subTitle: {
    fontSize: 13,
    color: "#D7D7D7",
    fontWeight: "400",
    marginBottom: 20,
  },
  input: {
    height: 50,
    backgroundColor: "#ffffff0d",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#ffffff99",
    padding: 16,
    color: "#FFFFFF",
    fontSize: 14,
    marginVertical: 13,
  },
  btnCont: {
    paddingVertical: 15,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 2,
    marginVertical: 40,
  },
  btnText: {
    fontSize: 15,
    fontWeight: "400",
    color: "#091425",
  },
  image: {
    width: 150,
    height: 150,
    borderRadius: 75, 
    borderWidth: 1,
    borderColor: "#ffffff99",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 20,
    marginBottom: 20, 
  },
  imageText: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "500",
    marginTop: 8,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)", 
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 10,
    width: "80%",
  },
  modalItem: {
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
  },
  modalItemFirst: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  modalText: {
    fontSize: 16,
    textAlign: "center",
    color: "#333333",
  },
  modalCancel: {
    paddingVertical: 15,
    borderRadius: 10,
    marginTop: 10,
    backgroundColor: "#092325",
  },
  modalCancelText: {
    fontSize: 16,
    textAlign: "center",
    color: "#FFFFFF",
  },
});
